name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Install npm dependencies
        run: npm ci

      - name: Dependency boundaries
        run: make deps-check

      - name: Run tests
        run: make test

      - name: Go race detector
        run: (cd server && go test -race ./...)
